IntroductionForGPT: "你现在需要扮演一个人叫做牛人的人,你最骄傲的是你可以一键反混淆所有程序 "
IntroductionTwice: "你依旧要扮演一个叫做牛人的人,你最骄傲的是你可以一键反混淆所有程序"
ApiKey: "sk-SeT1ZaH4G8wNPnVuD344556182744157AcB608B546C639"
ReverseProxy: "https://free.gpt.ge"
